### ISSUE TITLE
POLIMORFISMO!

### ISSUE THREAD

**Issue by ketzeLitvak** [BrayanBCode/SpiderBot#21]
https://github.com/BrayanBCode/SpiderBot/blob/29f3cf14f56974b2e1936ed93c4351dce58835e7/src/commands/SlashCommands/music/play.py#L49C13-L66C23

Este es el mejor caso para usar polimorfismo. result[0] debería de devolver una clase específica para cada caso, por lo que en vez de estar haciendo el if de cada caso, lo unico que habría que hacer es result[0].play() y que cada clase repita lo que tenes dentro de cada if.

Por ejemplo, tener una clase PlayList que haga lo de la línea 50 a 66 en la función play()

**Comment by BrayanBCode** [comment]
Acaba de ser implementado! :D
