### ISSUE TITLE
Pasar los mensajes a una clase de utilidades

### ISSUE THREAD

**Issue by ketzeLitvak** [BrayanBCode/SpiderBot#23]
https://github.com/BrayanBCode/SpiderBot/blob/29f3cf14f56974b2e1936ed93c4351dce58835e7/src/commands/SlashCommands/music/leave.py#L32

Se puede generar una clase nueva para poder armar los mensajes con mayor facilidad. La clase recibiria el interaction en el constructor y debería de tener métodos como "sendError" o "sendInformation", que ya tengan los colores seteados y simplemente tengas que mandar el string con el mensaje

**Comment by BrayanBCode** [comment]
Implemented brother
https://github.com/BrayanBCode/SpiderBot/blob/181ecc93b47e818de44dbfbd268522a8dd8ac940/src/base/utils/Logging/logger.py#L5
