### ISSUE TITLE
Se pueden poner los atributos en la clase para ayudar con el tipado

### ISSUE THREAD

**Issue by ketzeLitvak** [BrayanBCode/SpiderBot#27]
https://github.com/BrayanBCode/SpiderBot/blob/29f3cf14f56974b2e1936ed93c4351dce58835e7/src/base/classes/SpiderPlayer/player.py#L45-L61

Si se ponen los atributos dentro de la clase sueltos, fuera de las funciones, y se le ponen los tipados, el IDE te ayuda y sabe que dentro de la clase va a exisitir esos atributos. Es una forma de definirlos

**Comment by BrayanBCode** [comment]
Anotado!
